# Generated by Django 5.2.7 on 2026-01-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('tital', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('isPublic', models.BooleanField(default=True)),
            ],
        ),
    ]
