# Generated by Django 5.2.7 on 2026-01-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='tital',
            new_name='title',
        ),
    ]
